// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/lbc.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *BackendRequest) Validate() error {
	return nil
}
func (this *BackendResponse) Validate() error {
	return nil
}
