---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.24.0
    commands:
      - golangci-lint run -v -D errcheck

  - name: fmt
    image: golang:1.13-alpine
    commands:
      - set -o pipefail
      - apk add --update --upgrade --no-cache git
      - go get golang.org/x/tools/cmd/goimports
      - goimports -d . | (! grep .)

  - name: test
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go test -v -coverprofile=coverage.txt -covermode=atomic ./...

  - name: codecov
    group: publish
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
    depends_on:
      - test

  - name: build
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-X main.gitRev=${DRONE_COMMIT_SHA}" -o cacher-linux-x86_64

  - name: publish
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/packet/cacher
      tags:
        - ${DRONE_BRANCH/\//-}
        - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: push
    depends_on:
      - build
      - fmt
      - lint
      - test
